---
title: "Financial Options: A Monte Carlo Approach"
author: "Group 6: Trevor Isaacson, Noah Smith and Buzz Walter "
date: "12/7/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
set.seed(400)
library(tidyr)
library(tidyverse)
library(rmarkdown)
library(ggplot2)
library(dbplyr)
```

## Background

- Our project is based on a paper called "Options: A Monte Carlo Approach"
- Written by Phelim P. Boyle in 1977 and published in the Journal of Financial Economics
- Boyle is an Irish economist and a pioneer of quantitative finance
- He is best known for his use of Monte Carlo methods in option pricing

## Financial Terminology

- Stock: security ownership in a particular company 
  - ex: common stock of Apple is ~ $165
- Inflation Rate: rate at which the value of a currency is falling and the general level of prices for goods and services is rising
- Treasury Yield: yield of a US Treasury Bond matching investment duration
- Risk Free Rate: Represents the interest an investor would expect from a risk-free investment over a specific time
  - RFr = Treasury Yield - Inflation Rate

## The LogNormal Distribution




## What are options?

- Options are a very powerful and influential tool used heavily in financial markets
- It is a contract that is valued based on an underlying asset or security like a common stock or bond
  - Derivative, price is linked to price of underlying asset
- Options are more risky than common stock as the price moves faster
- Investors use options for income, to hedge risk and to speculate about future market movements

## How do options work?

- A single options contract represents 100 shares of the underlying asset it is representing
- Contract gives the buyer the right to buy the underlying asset at a specific price on a certain date
- Valuing options is essentially about determining the probabilities of future prices
  - The more likely something is to occur, the more expensive an option for that event
  - The less time to maturity, the less valuable the option 
  - Previous to these methods, there was no agreed upon method to determine option prices 
  
## European vs American Options



  
## Purpose of the Paper

- To show that Monte Carlo simulations provide a method to obtaining numerical solutions to option valuation problems
- Two other methods exist and this method should be used as a supplement
- Boyle's method is simple and flexible as it can be easily modified for different processes


## Monte Carlo

- g hat = max[St - E, 0]
- f(y) = lognormal distribution
- g(y) = result we get for final stock price
  - random variable because we include x tilda


## Black Scholes Model

- How do we find St



## Method Overview

- Method uses the fact that the distribution of terminal stock prices is determined by the process generating future stock price movements


## How it works




## Simulation















## References
https://www.investopedia.com/options-basics-tutorial-4583012