---
title: "Monte Carlo Simulations and Financial Options"
author: "Group 6: Trevor Isaacson, Noah Smith and Buzz Walter"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyr)
library(tidyverse)
library(rmarkdown)
library(ggplot2)
library(dbplyr)
library(tinytex)
```

**Introduction:**   
Monte Carlo integration is a statistical computing method used to approximate integrals based on random sampling.  Monte Carlo simulations are computer driven models that generate a large number of samples from a distribution that is characterized by the population of which the samples are being drawn from. The simulations achieve many results from the samples drawn and then averages those results to obtain a final estimate. These multidimensional simulations can then be used to model various outcomes that might be difficult otherwise with numerical integration.  These simulations can be used in many different areas and fields including finance, engineering, supply chain and many others.  
  
In order to apply what we have learned regarding Monte Carlo methods and simulations, our group was able to identify an article within statistical literature that applies Monte Carlo to financial options.  "Options: A Monte Carlo Approach" was published in 1977 by Phelim P. Boyle in the Journal of Financial Economics.  While the article is 44 years old, much of the paper can still be applied to today's financial markets and statistical approaches.  
  
Financial options are a very powerful and influential tool used heavily in financial markets.  An option is a contract that is valued based on a different underlying asset or security like a common stock.  A single options contract represents 100 shares of the underlying asset it is representing.  Because they 100 represent the underlying asset, options are more risky than common stock as the price moves faster.  The piece of the paper we wish to replicate simulates the process of generating returns on the underlying assets and then deriving the value of the option.  

**Financial Terminology:**



**History:**
The purpose of Boyle's paper was to show that Monte Carlo simulations provide another option of calculating numerical solution to option valuation and option valuation problems.  A few other methods were introduced around the same time as Boyle's paper.  A paper by Black and Scholes in 1973 detailed how option values would be obtained when market equilibrium conditions exist and Cox and Ross in 1976 showed that the value of a European call option can be obtained by discounting the expected maturity value of the option at the risk free rate.  Boyle's Monte Carlo method is simpler and more flexible compared to the other methods as it can be changed and modified to use different processes that govern the underlying stock returns and can change depending on the stock.  This method is a good supplement to the other two methods detailed above and each method has it's own advantages and disadvantages.   


**Methodology:**





**Simulation and Results:**
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
\newpage
**References:**   
Boyle, Phelim P. “Options: A Monte Carlo Approach.” Journal of Financial Economics, vol. 4, no. 3, 1977, pp. 323–338., https://doi.org/10.1016/0304-405x(77)90005-8. 
  